# Generated by Django 5.0.1 on 2024-01-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bichinhos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='bichinhos.tag'),
        ),
    ]
