# Generated by Django 5.0.1 on 2024-01-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bichinhos', '0002_tag_item_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='tag',
            name='nome',
            field=models.CharField(choices=[('', ''), ('GATO', 'Gato'), ('CACHORRO', 'Cachorro'), ('MACHO', 'Macho'), ('FEMEA', 'Fêmea')], default='', max_length=50),
        ),
    ]
