# Generated by Django 5.0.1 on 2024-01-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bichinhos', '0003_remove_item_categoria_alter_tag_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('', ''), ('GATO', 'Gato'), ('CACHORRO', 'Cachorro'), ('MACHO', 'Macho'), ('FEMEA', 'Fêmea')], default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
