# Generated by Django 5.0.1 on 2024-01-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bichinhos', '0004_remove_item_tags_item_categoria_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('', ''), ('GATO', 'Gato'), ('CACHORRO', 'Cachorro'), ('MACHO', 'Macho'), ('FEMEA', 'Fêmea')], default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='categoria',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='bichinhos.tag'),
        ),
    ]
