# Generated by Django 5.0.1 on 2024-01-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bichinhos', '0008_alter_item_tags_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='bichinhos.tag'),
        ),
    ]
